# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

default_target: all
.PHONY: default_target all clean cmake_check_build_system

# Variables
CMAKE_COMMAND = /usr/bin/cmake
CMAKE_SOURCE_DIR = /home/qwerti/Documents/GitHub/gituploader
CMAKE_BINARY_DIR = /home/qwerti/Documents/GitHub/gituploader

# Main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) --build $(CMAKE_BINARY_DIR)

# Clean target
clean:
	$(CMAKE_COMMAND) --build $(CMAKE_BINARY_DIR) --target clean

# Check build system integrity
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
